### ISSUE TITLE
[BUG] Code that worked fine in 1.21.5 stops working in 1.21.6 (fastboard)

### ISSUE THREAD

**Issue by smallsaga2** [ShaneBeee/SkBee#817]
### What happened?

I created a simple sidebar with skbee's fastboard that prints every second, showing the number of current users, player nicknames, and the current time.
Originally, the script was working fine in version 1.21.5, but when I updated it because server users wanted 1.21.6, it stopped working and Java error messages appeared in the log every second.

[21:14:34] [Server thread/WARN]: [Skript] Task #20 for Skript v2.11.2 generated an exception
java.lang.NoClassDefFoundError: Could not initialize class com.shanebeestudios.skbee.api.fastboard.base.adventure.FastBoard
	at SkBee-3.11.3.jar/com.shanebeestudios.skbee.api.fastboard.FastBoardAdventure.<init>(FastBoardAdventure.java:15) ~[SkBee-3.11.3.jar:?]
	at SkBee-3.11.3.jar/com.shanebeestudios.skbee.api.fastboard.FastBoardManager.getBoard(FastBoardManager.java:28) ~[SkBee-3.11.3.jar:?]
	at SkBee-3.11.3.jar/com.shanebeestudios.skbee.elements.fastboard.expressions.ExprFastBoardTitle.change(ExprFastBoardTitle.java:79) ~[SkBee-3.11.3.jar:?]
	at Skript-2.11.2.jar/ch.njol.skript.effects.EffChange.execute(EffChange.java:276) ~[Skript-2.11.2.jar:?]
	at Skript-2.11.2.jar/ch.njol.skript.lang.Effect.run(Effect.java:32) ~[Skript-2.11.2.jar:?]
	at Skript-2.11.2.jar/ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:40) ~[Skript-2.11.2.jar:?]
	at Skript-2.11.2.jar/ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:67) ~[Skript-2.11.2.jar:?]
	at Skript-2.11.2.jar/ch.njol.skript.lang.Trigger.execute(Trigger.java:33) ~[Skript-2.11.2.jar:?]
	at Skript-2.11.2.jar/ch.njol.skript.events.EvtPeriodical.execute(EvtPeriodical.java:103) ~[Skript-2.11.2.jar:?]
	at Skript-2.11.2.jar/ch.njol.skript.events.EvtPeriodical.lambda$postLoad$0(EvtPeriodical.java:62) ~[Skript-2.11.2.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78) ~[paper-1.21.6.jar:1.21.6-12-4781d28]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:474) ~[paper-1.21.6.jar:1.21.6-12-4781d28]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1659) ~[paper-1.21.6.jar:1.21.6-12-4781d28]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1529) ~[paper-1.21.6.jar:1.21.6-12-4781d28]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1251) ~[paper-1.21.6.jar:1.21.6-12-4781d28]
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310) ~[paper-1.21.6.jar:1.21.6-12-4781d28]
	at java.base/java.lang.Thread.run(Thread.java:1447) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.ExceptionInInitializerError [in thread "Server thread"]
	at SkBee-3.11.3.jar/com.shanebeestudios.skbee.api.fastboard.base.FastBoardBase.<clinit>(FastBoardBase.java:218) ~[SkBee-3.11.3.jar:?]
	... 17 more

### Steps to reproduce

1. Start the server and load the script
2. If fastboard is not turned on, turn it on with /sc on

![Image](https://github.com/user-attachments/assets/2cffb11e-52d5-4477-b36a-a3b0abdad49e)

### Expected behavior

Turn on fastboard with the /sc on command to display player nicknames, number of current users, and time on the Minecraft screen.

https://github.com/user-attachments/assets/0b9fd5e8-8de1-42c8-b250-1310805e3b39

### SkBee Version

3.11.3

### Server Version

#12-1.21.6 paper 

### SkBee Info

[13:59:11 INFO]: --- [SkBee Loading Info] ---
[13:59:11 INFO]: - Registry Elements successfully loaded
[13:59:11 INFO]: - [NBTAPI] Found Minecraft: 1.21.5! Trying to find NMS support
[13:59:11 INFO]: - [NBTAPI] NMS support 'MC1_21_R4' loaded!
[13:59:11 INFO]: - NBT Elements successfully loaded
[13:59:11 INFO]: - Text Component Elements successfully loaded
[13:59:11 INFO]: - Advancement Elements successfully loaded
[13:59:11 INFO]: - BossBar Elements successfully loaded
[13:59:11 INFO]: - Bound Elements successfully loaded
[13:59:11 INFO]: - Damage Source Elements successfully loaded
[13:59:11 INFO]: - Display Entity Elements successfully loaded
[13:59:11 INFO]: - Fastboard[Adventure] Elements successfully loaded
[13:59:11 INFO]: - Fishing Elements successfully loaded
[13:59:11 INFO]: - Game Event Elements successfully loaded
[13:59:11 INFO]: - Item Component Elements successfully loaded
[13:59:11 INFO]: - Particle Elements successfully loaded
[13:59:11 INFO]: - Property Elements successfully loaded
[13:59:11 INFO]: - RayTrace Elements successfully loaded
[13:59:11 INFO]: - Recipe Elements successfully loaded
[13:59:11 INFO]: - Scoreboard Elements successfully loaded
[13:59:11 INFO]: - Statistic Elements successfully loaded
[13:59:11 INFO]: - Structure Elements successfully loaded
[13:59:11 INFO]: - SwitchCase Elements successfully loaded
[13:59:11 INFO]: - Tick Manager Elements successfully loaded
[13:59:11 INFO]: - Villager Elements successfully loaded
[13:59:11 INFO]: - Virtual Furnace Elements disabled via config
[13:59:11 INFO]: - World Creator Elements successfully loaded
[13:59:11 INFO]: - Chunk Generator Elements successfully loaded
[13:59:11 INFO]: - Plugin is up to date!
[13:59:11 INFO]: --- [Server Info] ---
[13:59:11 INFO]: Server Version: Paper 1.21.5-113-ba7fb23 (MC: 1.21.5)
[13:59:11 INFO]: Skript Version: 2.11.2 (skriptlang-github)
[13:59:11 INFO]: Skript Addons:
[13:59:11 INFO]: - skRayFall v1.9.28
[13:59:11 INFO]: - SkQuery v4.3.2
[13:59:11 INFO]: - SkJson v5.2
[13:59:11 INFO]: - skript-particle v1.3.2
[13:59:11 INFO]: SkBee Version: 3.11.3
[13:59:11 INFO]: SkBee Website: https://github.com/ShaneBeee/SkBee

### Additional Information

This may be unrelated, but I asked gpt and they said the conflict was caused by a different Adventure API.

gpt : There was a problem in the static initialization block of the FastBoardBase class, and as a result, the FastBoardAdventure class cannot be initialized either.
Error occurred when initializing FastBoardBase class
→ Most likely it is a compatibility issue between Paper 1.21.6 version and the corresponding SkBee version of Adventure API

**Comment by Fusezion** [comment]
As far as I'm aware fastboard was only updated three days ago
![Image](https://github.com/user-attachments/assets/018c5cc0-2d2e-4955-9936-e95059337e30)

SkBee doesn't technically support 1.21.6 due to nbt-api and fastboard.
If you want to try an unofficial build you can download our artifact here
https://github.com/ShaneBeee/SkBee/actions/runs/15739345621/artifacts/3356672004

As a rule of thumb don't update versions until plugins have made releases explicitly stating it's supported.
SkBee breaks on most of every new version as NBT-API and FastBoard are both heavily nms/reflection based.

It'll be awhile longer before we officially support as it seems like the nbt-api only started working on 1.21.6 a few days ago.

**Comment by Fusezion** [comment]
Marking this as bug and completed once the release is out we'll close this
